### ISSUE TITLE
Switch the order of the two toilets

### ISSUE THREAD

**Issue by ppiro** [anlumo/dashboard#1]
'Stehklo' should come before 'Sitzklo' to reflect the layout of the physical space.

reported by @pascoda
![IMG_0656](https://github.com/anlumo/dashboard/assets/68238658/d0909fd4-0b86-47e2-a808-5dd51e9dbb08)

**Comment by kescherCode** [comment]
The above commit addresses the issue, therefore, this issue should be closed
